[package]
name = "logfmt"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
description="tracing_subscriber layer for writing out logfmt formatted events"
edition = "2018"

[dependencies] # In alphabetical order
tracing = { version = "0.1" }
tracing-subscriber = "0.2.15"

[dev-dependencies] # In alphabetical order
lazy_static = "1.4.0"
regex = "1.4.3"
