[package]
name = "influxdb_iox"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"
default-run = "influxdb_iox"

[workspace] # In alphabetical order
members = [
    "arrow_deps",
    "data_types",
    "generated_types",
    "influxdb_iox_client",
    "influxdb_line_protocol",
    "influxdb_tsm",
    "influxdb2_client",
    "ingest",
    "logfmt",
    "mem_qe",
    "mutable_buffer",
    "object_store",
    "packers",
    "panic_logging",
    "query",
    "read_buffer",
    "server",
    "test_helpers",
    "wal",
]

[profile.release]
debug = true

[profile.bench]
debug = true

[dependencies]
# Workspace dependencies, in alphabetical order
arrow_deps = { path = "arrow_deps" }
data_types = { path = "data_types" }
generated_types = { path = "generated_types" }
influxdb_iox_client = { path = "influxdb_iox_client" }
influxdb_line_protocol = { path = "influxdb_line_protocol" }
influxdb_tsm = { path = "influxdb_tsm" }
ingest = { path = "ingest" }
logfmt = { path = "logfmt" }
mem_qe = { path = "mem_qe" }
mutable_buffer = { path = "mutable_buffer" }
object_store = { path = "object_store" }
packers = { path = "packers" }
panic_logging = { path = "panic_logging" }
query = { path = "query" }
read_buffer = { path = "read_buffer" }
server = { path = "server" }
wal = { path = "wal" }

# Crates.io dependencies, in alphabetical order
byteorder = "1.3.4"
bytes = "1.0"
chrono = "0.4"
clap = "2.33.1"
csv = "1.1"
dirs = "3.0.1"
dotenv = "0.15.0"
env_logger = "0.7.1"
flate2 = "1.0"
futures = "0.3.1"
http = "0.2.0"
hyper = "0.14"
lazy_static = "1.4.0"
opentelemetry = { version = "0.12", default-features = false, features = ["trace", "tokio-support"] }
opentelemetry-jaeger = { version = "0.11", features = ["tokio"] }
prost = "0.7"
prost-types = "0.7"
# Forked to upgrade hyper and tokio
routerify = { git = "https://github.com/influxdata/routerify", rev = "274e250" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"
serde_urlencoded = "0.7.0"
snafu = "0.6.9"
structopt = "0.3.21"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.2", features = ["net"] }
tonic = "0.4.0"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-futures = "0.2.4"
tracing-opentelemetry = "0.11.0"
tracing-subscriber = "0.2.15"

[dev-dependencies] # In alphabetical order
assert_cmd = "1.0.0"
criterion = "0.3"
flate2 = "1.0"
hex = "0.4.2"
influxdb2_client = { path = "influxdb2_client" }
predicates = "1.0.4"
rand = "0.7.2"
reqwest = "0.11"
tempfile = "3.1.0"
test_helpers = { path = "test_helpers" }

[[bin]]
name = "cpu_feature_check"
path = "src/cpu_feature_check/main.rs"

[[bench]]
name = "encoders"
harness = false

[[bench]]
name = "line_parser"
harness = false

[[bench]]
name = "mapper"
harness = false

[[bench]]
name = "line_protocol_to_parquet"
harness = false

[[bench]]
name = "packers"
harness = false
