[package]
name = "influxdb_iox_client"
version = "0.1.0"
authors = ["Dom Dwyer <dom@itsallbroken.com>"]
edition = "2018"

[dependencies] # In alphabetical order
data_types = { path = "../data_types" }
reqwest = { version = "0.11.0", features = ["gzip", "json"] }
serde = "1.0.118"
thiserror = "1.0.23"
tokio = { version = "1.0", features = ["macros"] }

[dev-dependencies] # In alphabetical order
rand = "0.8.1"
serde_json = "1.0"
