[package]
name = "influxdb_iox_client"
version = "0.1.0"
authors = ["Dom Dwyer <dom@itsallbroken.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_types = { path = "../data_types" }
reqwest = { version = "0.10.10", features = ["gzip", "json"] } # Latest release using tokio 0.2
serde = "1.0.118"
thiserror = "1.0.23"
tokio = { version = "0.2", features = ["net", "tcp", "macros"] }

[dev-dependencies]
rand = "0.8.1"
serde_json = "1.0"
