[package]
name = "mem_qe"
version = "0.1.0"
authors = ["Edd Robinson <me@edd.io>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow_deps = { path = "../arrow_deps" }
chrono = "0.4"
croaring = "0.4.5"
crossbeam = "0.7.3"
env_logger = "0.7.1"
human_format = "1.0.3"
packers = { path = "../packers" }
snafu = "0.6.8"
tracing = "0.1"

[dev-dependencies] # In alphabetical order
criterion = "0.3"
