[package]
name = "server"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6"
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1"
data_types = { path = "../data_types" }
generated_types = { path = "../generated_types" }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
query = { path = "../query" }
mutable_buffer = { path = "../mutable_buffer" }
read_buffer = { path = "../read_buffer" }
object_store = { path = "../object_store" }
tracing = "0.1"
tokio = { version = "0.2", features = ["full"] }
arrow_deps = { path = "../arrow_deps" }
futures = "0.3.7"
bytes = "0.5"
chrono = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"]}
flatbuffers = "0.6"
crc32fast = "1.2.0"
snap = "1.0.0"
