[package]
name = "query"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2018"
description = "IOx Query Interface and Executor"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# This create is designed to be independent of the rest of the IOx
# server and specific storage systems such as Mutable Buffer and Read Buffer.
#
# The rationale for this is to:
#
# 1. Keep change/compile/link time down during development when working on just this crate
# 2. Allow for query logic testing without bringing in all the storage systems.



[dependencies]
snafu = "0.6.2"
async-trait = "0.1"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"
croaring = "0.4.5"
chrono = "0.4"

arrow_deps = { path = "../arrow_deps" }
sqlparser = "0.6.1"
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
data_types = { path = "../data_types" }
test_helpers = { path = "../test_helpers" }
