[package]
name = "influxdb_tsm"
version = "0.1.0"
authors = ["Edd Robinson <me@edd.io>"]
edition = "2018"

[dependencies] # In alphabetical order
integer-encoding = "1.0.7"
snafu = "0.6.2"
snap = "1.0.0"
tracing = "0.1"

[dev-dependencies] # In alphabetical order
flate2 = "1.0"
hex = "0.4.2"
rand = "0.7.2"
test_helpers = { path = "../test_helpers" }
